[package]
name = "od_gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
od_core = { path = "../od_core" }
iced = { git = "https://github.com/iced-rs/iced", branch="0.4" }
rfd = "0.7.0"
