[package]
name = "od_gui_egui"
version = "0.1.0"
edition = "2021"

[dependencies]
od_core = { path = "../od_core" }
od_module_elf = { path = "../modules/elf" }
eframe = "0.21"
rfd = "0.11"
tokio = { version = "1.27", features = ["full"] }
