name: clippy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install libatk1.0-dev libgtk-3-dev
    - name: Install nightly
      run: |
        rustup toolchain add nightly --component clippy
    - name: Build
      run: cargo +nightly clippy
    
