name: rustfmt

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install beta
      run: |
        rustup toolchain add beta --component rustfmt
    - name: Build
      run: cargo +beta fmt -- --check
    
